sudo: required
dist: trusty
services:
  - docker
before_install:
  - docker pull nimlang/nim
script:
  - docker run nimlang/nim nim --version
  - docker run -v "$(pwd):/project" -w /project nimlang/nim sh -c "apt-get update && apt-get install -y libgnutls28-dev libgnutls30 && nim c -p:src -r tests/test_sign.nim"
